spring:
  application:
    name: core-banking-legacy
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/core_banking_legacy}
    username: ${SPRING_DATASOURCE_USERNAME:corebanking}
    password: ${SPRING_DATASOURCE_PASSWORD:corebanking}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: ${SERVER_PORT:8081}
